name: Lesson 1

on:
  push:
    branches: [ main ]
    paths:
    - .github/workflow/lesson1.yml
    - lesson1/*
  pull_request:
    branches: [ main ]
    paths:
    - .github/workflow/lesson1.yml
    - lesson1/*

jobs:
  build1:
    name: Lesson 1
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build and Run
      run: |
        cd lesson1
        dotnet build
        dotnet run
